config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'reviews/create'
  # get 'reviews/show'
  # get 'reviews/index'
  # get 'bookings/new'
  # get 'bookings/create'
  # get 'bookings/show'
  # get 'bookings/index'
  # get 'spaceships/index'
  # get 'spaceships/show'
  devise_for :users
  root to: 'spaceships#index'
  resources :spaceships, only: [:index, :show] do
    resources :bookings, only: [:new, :create]

  end

  resources :bookings, only: [:index]

  resources :bookings, only: [:new, :create] do
    resources :reviews, only: [:new, :create, :show, :index]


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship
  validate :possible_in_datetime_range

  def possible_in_datetime_range
    return unless start_at && end_at
    range = start_at..end_at
    errors.add(:booking, 'Spaceship unavailable during that time') unless spaceship.available?(range)
  end

    private

  def self.overlapping(range)
    return all if range.blank?
      where(<<~SQL, range_start: range.first, range_end: range.last)
        (start_at BETWEEN :range_start AND :range_end)
        OR (end_at BETWEEN :range_start AND :range_end)
        OR (start_at < :range_start AND :range_end < end_at)
      SQL
  end
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: true
  validates :seat, presence: true
  validates :price_per_day, presence: true
  validates :address, presence: true

  def average_rating
    bookings_with_rating = bookings.where.not(rating: nil)
    return false if bookings_with_rating.empty?

    bookings_with_rating.average(:rating)
  end

  def available?(date_range)
    bookings.overlapping(date_range).empty?
  end
end

app/models/user.rb
 class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spaceships
  has_many :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking.spaceship = @spaceship
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render 'spaceships/show', locals: {booking: @booking, spaceship: @spaceship}
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @spaceship = Spaceship.find(params[:spaceship_id])
  end

  def index
    @bookings = Booking.where(user: current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_at, :end_at, :user_id, :spaceship_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @booking.review = params[:booking][:review]
    @booking.rating = params[:booking][:rating]
    if @booking.save(validate: false)
      redirect_to bookings_path
    else
      @bookings = Booking.where(user: current_user)
      render 'bookings/index'
    end
  end

  def show
    @review = Review.find(params[:id])
    @booking = Booking.where(booking_id: @booking.id)
  end

  def index
    @reviews = Review.all
  end

  private

  def review_params
    params.require(:booking).permit(:review, :rating)
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @spaceships = Spaceship.all
  end

  def show
    @spaceship = Spaceship.where.not(latitude: nil, longitude: nil) && Spaceship.find(params[:id])
    @markers = [{
      lng: @spaceship.longitude,
      lat: @spaceship.latitude
    }]
    @disableddate = @spaceship.bookings.map do |booking|
      {
        from: booking.start_at.strftime("%Y-%m-%d"),
        to: booking.end_at.strftime("%Y-%m-%d")
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="booking-info">
  <div class="book-panel">
    <div class="book-heading">Book Spaceship</div>
      <div class="book-body" id="disabled-date" data-disabled-date="<%= disableddate %>">

          <%= simple_form_for [spaceship, booking] do |f| %>
            <%= f.input :start_at, as: :string, placeholder: 'jj/mm/yy' %>
            <%= f.input :end_at, as: :string , placeholder: 'jj/mm/yy' %>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1> My Bookings : <%= current_user.email %></h1>
  <% @bookings.each do |booking| %>
    <div class="panel panel-default">
      <div class="panel-heading"><%= booking.spaceship.title %></div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4">

              <div class="banner-booking" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= booking.spaceship.photo %>);">
              </div>
            </div>

            <!---------------------------- MODAL ------------------------->
            <div class="col-md-8">
              <p><strong> Dates </strong> : <%= booking.start_at%> to <%= booking.end_at %></p>
            <% if booking.review == nil %>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                Add a Review
              </button>

                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Your Review</h4>
                      </div>
                      <div class="modal-body">
                      <%=  render 'reviews/new', url: booking_reviews_path(booking), booking: booking  %>
                      </div>
                    </div>
                  </div>
                </div>
<!------------------------- MODAL END ----------------------------------------->

            <% else %>

              <p><strong> My Review </strong> : <%= booking.review %></p>
              <p><strong> My Rating </strong> : <%= booking.rating %></p>
            <% end %>
            <%= link_to "See spaceship", spaceship_path(booking.spaceship_id), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>

<%= @booking.start_at %>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SNASA</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_new.html.erb
<div class="panel panel-default">
    <div class="panel-body">
      <%= simple_form_for booking, url: url, method: :post do |f| %>
        <%= f.input :review %>
        <%= f.input :rating, collection: 1..5 %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Snails rule the world <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
  <img class="avatar-large" src='https://animationfascination.files.wordpress.com/2015/07/tbf_ep206b_1908_rgb.jpg'/>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Reservations", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Spaceships", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Log In",  new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src='https://res.cloudinary.com/dyzsumrcv/image/upload/v1550672177/cible.jpg' class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><%=  link_to "Log Out", destroy_user_session_path, :method => :delete %> </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Reservations</a></li>
        <li><a href="#">Spaceships</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/spaceships/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <div class="container"></div>
    <ol class="carousel-indicators">
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <div class="main-item">

          <div class="carousel-caption">
            <h1>SNASA</h1>
            <p>Snail National Aeronautics and Space Administration</p>
            <%= link_to "Come with us", new_user_registration_path, :class => "btn btn-ghost" %>
          </div>
        </div>
      </div>

      <% @spaceships.each do |spaceship| %>
        <div class="item " style="background-image: linear-gradient(to bottom, rgba(255,0,0,0), #181C1F), url(<%= spaceship.photo %>)">
          <%= link_to spaceship_path(spaceship) do %>
              <div class="carousel-caption" >
                 <h2><%= spaceship.title %></h2>
                 <p><%= spaceship.seat %> places</p>
                 <h2 class="card-trip-pricing"><%= spaceship.price_per_day %> €</h2>
              </div>
          <%end%>
        </div>
      <%end%>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>
</div>

app/views/spaceships/index.html.erb
<%= render 'carousel' %>

<div class="container">
  <div class="row">
    <% @spaceships.each do |spaceship| %>
      <div class="col-xs-12 col-sm-4 bigcard">
        <%= link_to spaceship_path(spaceship) do %>
            <div class="card-trip">
              <%= image_tag(spaceship.photo) %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= spaceship.title %></h2>
                  <p><%= spaceship.seat %> places</p>
                </div>
                <h2 class="card-trip-pricing"><%= spaceship.price_per_day %> €</h2>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/spaceships/show.html.erb
<div class="background-show">
  <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @spaceship.photo %>)">
    <div class="container show-container">
        <h1>Rent <%= @spaceship.title %> <strong>awesome experiences</strong> to <strong>adventurous snails</strong>!</h1>
        <p>Change your life and go to the space with all your friends</p>
      </div>
    </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1 class="main-title"><%= @spaceship.title %></h1>
            <div class="show-rating">
              <p class ="show-text">Average Rating :
                <% if @spaceship.average_rating %>
                  <% @spaceship.average_rating.to_i.times do  %>
                    <span class="glyphicon glyphicon-star"></span>
                  <% end %>
                <% else %>
                  <p class ="show-text">Ce vaisseau n'a pas encore de note</p>
                <% end %>
              </p>
            </div>
            <div class="show-information">Informations</div>
              <div class="panel-body">
                <ul class="list-group">
                  <li class="list-show"><%= @spaceship.seat %> seats</li>
                  <li class="list-show"><%= @spaceship.price_per_day %> €</li>
                  <li class="list-show">Address : <%= @spaceship.address %></li>
                </ul>
              </div>

            <div class="show-description">
              <div class="description-heading">Description</div>
              <p class="show-text"><%= @spaceship.description %></p>
            </div>

          <div class="show-review">
            <div class="review-heading">Reviews</div>
              <div class="panel-body">
                <% @spaceship.bookings.each do |booking| %>
                  <% if booking.review != nil %>
                    <p class ="show-text"><%= booking.user.first_name %> : <%= booking.review %></p><hr>
                  <% end %>
                <% end %>
              </div>
          </div>

        <div
          id="map"
          style="width: 100%;
          height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        </div>
      </div>


      <div class="col-md-4">
          <%= render 'bookings/new', booking: Booking.new, spaceship: @spaceship, disableddate: @disableddate.to_json  %>
      </div>
    </div>
  </div>
</div>